variables:
  IMAGE_NAME: nextflow-runner
build:
  script:
    - aws ecr get-login --no-include-email --region us-west-2 | sh
    - COMMIT_HASH=$(git rev-parse --short HEAD)
    - TAG="${DOCKER_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}"
    - docker build -t $TAG .
    - docker push $TAG